name: Sync gh-pages from upstream

on:
  schedule:
    - cron: '0 * * * *'  # Every hour
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo (your fork)
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          persist-credentials: false  # we'll re-auth with a token

      - name: Configure Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

      - name: Add upstream and hard reset
        run: |
          git remote add upstream https://github.com/GriffithsLab/brainmodes2025-website.git
          git fetch upstream gh-pages
          git reset --hard upstream/gh-pages

      - name: Push to your fork
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git
          git push origin gh-pages --force
